apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kisanhaat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/adityaydv13/kisanhaat-manifest.git'
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kisanhaat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
